data:
  train_urls:
    - "/home/resenv/Desktop/levanterForAnticipation/data/jsbChorales/tokenized-events-Train.txt"
  validation_urls:
    - "/home/resenv/Desktop/levanterForAnticipation/data/jsbChorales/tokenized-events-Validation.txt"
  tokenizer: "passthrough"
  plaintext: True
  vocab_size: 55028
  enforce_eos: False
lora:
  r: 32 # rank of LoRA transform
  alpha: 8.0 # scaling factor for LoRA transform
  dropout: 0.0 # droupout probability for LoRA layers
initialize_from_hf: stanford-crfm/music-medium-800k
trainer:
  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 16
  num_train_steps: 2001
  train_batch_size: 512
  per_device_eval_parallelism: 1
  steps_per_eval: 50
  id: "jsbChorales_run03"
  wandb:
    project: "resenv-tower-02-levanter"
    tags: ["jsbChorales", "lora", "anticipation"]

  checkpointer:
    base_path: "/home/resenv/Desktop/levanterForAnticipation/checkpoints"
    save_interval: 30m
    keep:
      - every: 1000

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  parameter_axis_resources:
    embed: "data"
optimizer:
  # values in qlora paper
  learning_rate: 2e-4
  weight_decay: 0.0
  lr_schedule: "constant"
